# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import outsource.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=50)),
                ('user_type', models.IntegerField(choices=[(0, '유저'), (1, '카페')], default=0)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to=outsource.models.beverage_directory_path)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_coupon_update', models.DateTimeField()),
                ('coupon_progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.Beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('locationString', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('outsource.baseuser',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(null=True, upload_to=outsource.models.user_directory_path)),
                ('birth_year', models.IntegerField(default=1998)),
                ('birth_month', models.IntegerField(default=8)),
                ('birth_day', models.IntegerField(default=18)),
                ('gender', models.BooleanField(default=True)),
                ('favorite_cafe', models.ManyToManyField(null=True, to='outsource.Cafe')),
            ],
            options={
                'abstract': False,
            },
            bases=('outsource.baseuser',),
        ),
        migrations.AddField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.Cafe'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='outsource.User'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='outsource.Cafe'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='outsource.User'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='cafes', to='outsource.Order'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beverages', to='outsource.Cafe'),
        ),
    ]
