# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0003_auto_20170624_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, '유저'), (1, '카페')], default=0),
        ),
    ]
