# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import outsource.models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0004_auto_20170625_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafe_image',
            field=models.ImageField(null=True, upload_to=outsource.models.cafe_directory_path),
        ),
    ]
