# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0006_mydevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL),
        ),
    ]
