# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0007_auto_20170726_1838'),
        ('outsource', '0004_auto_20170624_0517'),
    ]

    operations = [
    ]
