# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0008_merge_20170801_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.BooleanField(choices=[(0, '가격할인'), (1, '쿠폰추가')], default=0)),
                ('price', models.IntegerField(default=0)),
                ('to_time', models.DateTimeField()),
                ('from_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='beverage',
        ),
        migrations.AddField(
            model_name='beverage',
            name='coupon_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='beverages',
            field=models.ManyToManyField(to='outsource.Beverage'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.BooleanField(choices=[(0, '일반결제'), (1, '쿠폰결제'), (2, '이벤트결제')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='beverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='outsource.Beverage'),
        ),
        migrations.AddField(
            model_name='event',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='outsource.Cafe'),
        ),
    ]
