# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0009_auto_20170801_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='outsource.Beverage'),
        ),
    ]
