# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0012_remove_event_beverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='beverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='outsource.Beverage'),
        ),
    ]
