# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0013_event_beverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(0, '가격할인'), (1, '쿠폰추가')], default=0),
        ),
    ]
