# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0014_auto_20170801_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='beverages',
            new_name='beverage',
        ),
    ]
