# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0017_auto_20170807_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='beverage',
            new_name='beverages',
        ),
    ]
