# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0020_auto_20170808_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_time',
            field=models.DateTimeField(null=True),
        ),
    ]
