# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0022_auto_20170808_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='beverages',
        ),
        migrations.AddField(
            model_name='order',
            name='options',
            field=models.ManyToManyField(to='outsource.BeverageOption'),
        ),
    ]
