# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0025_auto_20170811_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
