# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0028_beverageoption_shot_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, '일반결제'), (1, '쿠폰결제'), (2, '이벤트결제')], default=0),
        ),
    ]
