# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0030_socialuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='tag',
            field=models.CharField(default='', max_length=50),
        ),
    ]
