# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0031_cafe_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_event', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=100)),
                ('alert_life', models.DateTimeField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.Cafe')),
            ],
        ),
    ]
