# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0033_auto_20171012_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverageoption',
            name='type',
            field=models.IntegerField(choices=[(0, '커피&에스프레소'), (1, '에이드&스무디'), (2, '차'), (3, '디저트'), (4, '기타')], default=0),
        ),
    ]
