# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-05 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0035_auto_20171104_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='email',
        ),
    ]
