# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0038_auto_20171109_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
