# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-15 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0040_cafe_min_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='current_order_num',
            new_name='the_pay_order_num',
        ),
    ]
