# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0041_auto_20171215_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeverageOrderOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('shot_num', models.IntegerField(default=0)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.Beverage')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderOptionSelector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.BeverageOrderOption')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.OptionSelection')),
            ],
        ),
        migrations.RemoveField(
            model_name='beverageoption',
            name='is_ice',
        ),
        migrations.RemoveField(
            model_name='beverageoption',
            name='shot_num',
        ),
        migrations.RemoveField(
            model_name='beverageoption',
            name='size',
        ),
        migrations.RemoveField(
            model_name='beverageoption',
            name='whipping_cream',
        ),
        migrations.AddField(
            model_name='beverageoption',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beverageoption',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beverageoption',
            name='beverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='outsource.Beverage'),
        ),
        migrations.AddField(
            model_name='optionselection',
            name='beverageOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='outsource.BeverageOption'),
        ),
        migrations.AddField(
            model_name='beverageorderoption',
            name='options',
            field=models.ManyToManyField(to='outsource.OrderOptionSelector'),
        ),
    ]
