# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0042_auto_20180102_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverageorderoption',
            name='options',
        ),
        migrations.AlterField(
            model_name='orderoptionselector',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='outsource.BeverageOrderOption'),
        ),
    ]
