# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0043_auto_20180102_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='options',
            field=models.ManyToManyField(to='outsource.BeverageOrderOption'),
        ),
    ]
