# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0046_auto_20180103_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderoptionselector',
            name='selection',
        ),
        migrations.AlterField(
            model_name='beverageorderoption',
            name='options',
            field=models.ManyToManyField(to='outsource.OptionSelection'),
        ),
        migrations.DeleteModel(
            name='OrderOptionSelector',
        ),
    ]
