# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0047_auto_20180103_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverageoption',
            name='price',
        ),
        migrations.AddField(
            model_name='optionselection',
            name='add_price',
            field=models.IntegerField(default=0),
        ),
    ]
