# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0049_auto_20180108_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='have_shot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beverageoption',
            name='one_selector',
            field=models.BooleanField(default=False),
        ),
    ]
