# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0050_auto_20180118_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='add_shot_price',
            field=models.IntegerField(default=0),
        ),
    ]
