# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0052_beverageorderoption_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='options',
            new_name='beverages',
        ),
    ]
