# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0053_auto_20180124_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='coupon_payment',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='can_use_coupon',
        ),
        migrations.AddField(
            model_name='cafe',
            name='coupon_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, '일반결제'), (1, '휴대폰결제'), (2, '계좌결제')], default=0),
        ),
    ]
