# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0054_auto_20180126_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_end',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_making',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
