# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import outsource.models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0055_auto_20180201_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=outsource.models.beverage_directory_path),
        ),
    ]
